-- V1 — initial schema for the domain model v1 (docs/domain-model.md).
--
-- Conventions:
--  * Written in the intersection of PostgreSQL and H2 (`MODE=PostgreSQL`) syntax, so the same file
--    applies to the local zero-install H2 database and to real Postgres (docs/TOOLING.md).
--  * Identifiers are unquoted lowercase snake_case — Postgres folds them, H2 does the same under
--    `DATABASE_TO_LOWER=TRUE`.
--  * Money is `bigint`, always minor units, never numeric/float — the single most important
--    correctness rule in this schema (docs/domain-model.md).
--  * Enums are `varchar` + a check constraint rather than a native Postgres enum type: adding a
--    value later is an ordinary migration instead of a type alteration, and it is portable to H2.
--  * Primary keys are UUIDv7, generated by the application, not the database — they are
--    time-sortable, which is what makes them usable directly as ADR-0015 pagination cursors.
--  * AuditLogEntry is deliberately absent: ADR-0012 puts the audit log in Phase 2, and Phase 1 is
--    append-only, so there is nothing to audit yet.

create table users (
    id            uuid         primary key,
    email         varchar(320) not null,
    password_hash varchar(255),
    display_name  varchar(120) not null,
    is_ghost      boolean      not null default false,
    created_at    timestamp with time zone not null,
    -- docs/domain-model.md scopes uniqueness to non-ghost users. Phase 1 has no ghost users
    -- (they are Phase 2, FEATURES.md §b) and H2 has no partial indexes, so this is the stricter
    -- whole-table constraint for now; the Phase 2 ghost-user migration must relax it to a
    -- Postgres partial unique index (`where is_ghost = false`) once H2 is no longer a target.
    constraint ux_users_email unique (email)
);

create table ledgers (
    id               uuid        primary key,
    name             varchar(120) not null,
    -- ISO 4217 alphabetic code. `Ledger.defaultCurrency`'s own default value is still an open
    -- question in docs/domain-model.md, so this column deliberately has no database default.
    default_currency char(3)     not null,
    created_at       timestamp with time zone not null,
    -- Phase 2 (group archiving); null in Phase 1.
    archived_at      timestamp with time zone
);

-- ADR-0004: "personal" vs "shared" is never stored — it is derived from the membership count.
-- There is intentionally no ledger `type`/`is_personal` column for any query to branch on.
create table memberships (
    id        uuid        primary key,
    ledger_id uuid        not null references ledgers (id),
    user_id   uuid        not null references users (id),
    role      varchar(16) not null,
    joined_at timestamp with time zone not null,
    constraint ux_memberships_ledger_user unique (ledger_id, user_id),
    constraint ck_memberships_role check (role in ('OWNER', 'MEMBER'))
);

create index ix_memberships_user on memberships (user_id);

create table expenses (
    id                  uuid         primary key,
    ledger_id           uuid         not null references ledgers (id),
    -- Expenses point at a membership, not a user, so ledger math survives ADR-0014's
    -- anonymize-instead-of-delete policy.
    payer_membership_id uuid         not null references memberships (id),
    amount              bigint       not null,
    currency            char(3)      not null,
    category            varchar(64)  not null,
    note                varchar(1000),
    -- The expense's real-world date, deliberately distinct from created_at. Named `expense_date`
    -- rather than `date` to stay clear of both dialects' keyword lists.
    expense_date        date         not null,
    created_at          timestamp with time zone not null,
    split_type          varchar(16)  not null default 'EQUAL',
    is_locked           boolean      not null default false,
    constraint ck_expenses_amount_positive check (amount > 0),
    constraint ck_expenses_split_type check (
        split_type in ('EQUAL', 'EXACT', 'PERCENTAGE', 'WEIGHTED', 'ITEMIZED')
    )
);

-- Supports ADR-0015's cursor pagination over a ledger's expense history: the UUIDv7 id is the
-- cursor, so (ledger_id, id) is the exact access path.
create index ix_expenses_ledger_id on expenses (ledger_id, id);

create table splits (
    id            uuid   primary key,
    expense_id    uuid   not null references expenses (id) on delete cascade,
    membership_id uuid   not null references memberships (id),
    -- This member's settled share in minor units. The invariant that all splits of an expense sum
    -- to exactly expenses.amount is enforced in `core`'s domain layer (ADR-0001), not by a
    -- constraint — SQL cannot express it without a trigger, and the rule belongs where every
    -- client shares it.
    amount        bigint not null,
    -- Raw percentage (0-100) or weight the share was derived from; null for EQUAL/EXACT.
    share_value   bigint,
    constraint ux_splits_expense_membership unique (expense_id, membership_id)
);

create index ix_splits_membership on splits (membership_id);

create table settlements (
    id                 uuid    primary key,
    ledger_id          uuid    not null references ledgers (id),
    from_membership_id uuid    not null references memberships (id),
    to_membership_id   uuid    not null references memberships (id),
    amount             bigint  not null,
    currency           char(3) not null,
    note               varchar(1000),
    created_at         timestamp with time zone not null,
    constraint ck_settlements_amount_positive check (amount > 0),
    constraint ck_settlements_distinct_parties check (from_membership_id <> to_membership_id)
);

create index ix_settlements_ledger_id on settlements (ledger_id, id);
